magiccfg: fill in missing Introduction node of english translation, and compile both versions

diff --git a/apps/magiccfg/doc/Makefile b/apps/magiccfg/doc/Makefile
--- a/apps/magiccfg/doc/Makefile
+++ b/apps/magiccfg/doc/Makefile
@@ -5,11 +5,13 @@ ifeq ($(HCP),)
 HCP = hcp
 endif
 
+INCLUDES := $(wildcard include/*.ui)
+
 .PHONY: all
 
-all: magiccfg.hyp magiccfg.txt
+all: magiccfg_en.hyp magiccfg_en.txt magiccfg_de.hyp magiccfg_de.txt
 
-magiccfg.txt: magiccfg.u
+magiccfg_en.txt: magiccfg.u $(INCLUDES)
 	@if $(UDO) --version >/dev/null 2>&1; then \
 		echo $(UDO) --asc -o $@ $<; \
 		$(UDO) --asc -o $@ $<; \
@@ -17,7 +19,15 @@ magiccfg.txt: magiccfg.u
 		echo "UDO not found, help file not compiled" >&2; \
 	fi
 
-magiccfg.stg: magiccfg.u
+magiccfg_de.txt: magiccfg.u $(INCLUDES)
+	@if $(UDO) --version >/dev/null 2>&1; then \
+		echo $(UDO) -DGERMAN --asc -o $@ $<; \
+		$(UDO) -D GERMAN --asc -o $@ $<; \
+	else \
+		echo "UDO not found, help file not compiled" >&2; \
+	fi
+
+magiccfg_en.stg: magiccfg.u $(INCLUDES)
 	@if $(UDO) --version >/dev/null 2>&1; then \
 		echo $(UDO) --stg -o $@ $<; \
 		$(UDO) --stg --no-hypfile -o $@ $<; \
@@ -26,7 +36,24 @@ magiccfg.stg: magiccfg.u
 		echo "UDO not found, help file not compiled" >&2; \
 	fi
 
-magiccfg.hyp: magiccfg.stg
+magiccfg_en.hyp: magiccfg_en.stg
+	@if $(HCP) --version >/dev/null 2>&1 && test -f $<; then \
+		echo $(HCP) -o $@ $<; \
+		$(HCP) -o $@ $<; \
+	else \
+		echo "HCP not found, help file not compiled" >&2; \
+	fi
+
+magiccfg_de.stg: magiccfg.u $(INCLUDES)
+	@if $(UDO) --version >/dev/null 2>&1; then \
+		echo $(UDO) -DGERMAN --stg -o $@ $<; \
+		$(UDO) -D GERMAN --stg --no-hypfile -o $@ $<; \
+		sed -i 's/e@gmx/e@@gmx/' $@; \
+	else \
+		echo "UDO not found, help file not compiled" >&2; \
+	fi
+
+magiccfg_de.hyp: magiccfg_de.stg
 	@if $(HCP) --version >/dev/null 2>&1 && test -f $<; then \
 		echo $(HCP) -o $@ $<; \
 		$(HCP) -o $@ $<; \
@@ -35,4 +62,4 @@ magiccfg.hyp: magiccfg.stg
 	fi
 
 clean::
-	$(RM) *.hyp *.ref *.stg *.uls *.ulh *.uhs *.ula *.uha udo*.gif magiccfg.txt
+	$(RM) *.hyp *.ref *.stg *.uls *.ulh *.uhs *.ula *.uha udo*.gif magiccfg.txt magiccfg_de.txt
